### ISSUE TITLE
help cannot connect SSH

### ISSUE THREAD

**Issue by avenbreaks** [scaleway/scaleway-sdk-js#220]
Hello, scaleway VM Cannot connect to SSH port 22, inboud open port 22 

![image](https://user-images.githubusercontent.com/93043826/200706075-bb710cac-37ca-4aee-b386-b692b60b8dc1.png)

**Comment by Vinzius** [comment]
Hi Avenbreaks,

It seems this issue isn't related to the sdk-js, but to a specific product.
If so, then please reach out in the [slack community](https://slack.scaleway.com/).

If you still think this issue is related to the Javascript SDK, feel free to re-open this MR.

Have a nice day,
VIncent
