### ISSUE TITLE
Scaleway sdk with remix run leads to TypeError: Invalid response object

### ISSUE THREAD

**Issue by till1993** [scaleway/scaleway-sdk-js#509]
Hi everyone,

I encountered a bug with the Scaleway SDK for JavaScript. We are using your SDK in our Remix.run application to create or fetch tokens for accessing serverless containers.

Starting with version 0.1.0-beta35, all requests to Scaleway APIs are failing with the error "TypeError: Invalid response object."

The issue can be traced back to the following check in the index.cjs file:

``` 
const responseParser = (unmarshaller, responseType) => async response => {
  if (!(response instanceof Response)) {
    throw new TypeError('Invalid response object');
  }
  ....
}
  ```
  
  
However, the Response object is not unique within the Remix/React-Router context. They have encountered similar issues that can be found here: 
related issue: https://github.com/remix-run/remix/issues/4741
PRs to fix it: 
https://github.com/remix-run/react-router/pull/9690
https://github.com/remix-run/remix/pull/4782
 
I suggest replacing the instanceof Response check with something like:
```
export function isResponse(value: any): value is Response {
  return (
    value != null &&
    typeof value.status === "number" &&
    typeof value.statusText === "string" &&
    typeof value.headers === "object" &&
    typeof value.body !== "undefined"
  );
}
```

We are currently stuck on version 0.1.0-beta34 until this issue is resolved. Please let me know if you have any further questions.

**Comment by Vinzius** [comment]
Hi @till1993,

Thanks for taking time to open this issue, and adding a suggestion :-)

We'll take a look next week!

Have a nice week-end,
Vincent

**Comment by Vinzius** [comment]
Hello 😄 

I modified a bit your code to have `unknown` as input and pass our pipelines (#536). Feel free to suggest a different approach.

Question for you: do you want to test this branch (e.g. with yalc) before we merge, or is it okay to proceed?

Have a nice week,
Vincent

**Comment by Vinzius** [comment]
@till1993 I guess it's okay to proceed. We'll merge; it should be included it in the next version (early this week).
