### ISSUE TITLE
[TEM] Unable to set "reply to" address

### ISSUE THREAD

**Issue by StructuralRealist** [scaleway/scaleway-sdk-js#848]
## Feature request
Ability to set the reply to address when creating an email:
```
api.createEmail({replyTo: "someone@example.com"})
```

I'm not sure if this is a limitation of TEM or just the SDK. I cannot find anything about it in the docs.

### Use case
For example when users submit a form which triggers an email to the admin. Instead of replying to the noreply address it would be better to reply to the email address provided in the form.

**Comment by quantumsheep** [comment]
Hey 👋 The Transactional Email team is now aware of the issue and will add the field very soon :)

**Comment by yfodil** [comment]
Hello 👋, it is now possible to specify the "Reply-To" address using the new additional headers parameter:
```
api.createEmail({
  from: {
    email: 'sender@example.com',
  },
  to: [{
    email: 'recipient@example.com',
  }],
  subject: 'Your Subject Here',
  text: 'Your email content here.',
  additionalHeaders: [
    {
      key: 'Reply-To',
      value: 'someone@example.com',
    },
  ],
});

```
